name: flutterwallpaper
description: Wallpaper App
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.11.3+17
  flutter_youtube: ^1.1.0
  path_provider: ^0.4.1
  flutter_staggered_grid_view: ^0.2.2
  dio: ^1.0.6
  cloud_firestore: ^0.8.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
     - images/bgtry.png