name: Build Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      commit_secret: ${{secrets.commit_secret}}
      commit_email: ${{secrets.commit_email}}
      commit_name: ${{secrets.commit_name}}
      app_sentry: ${{secrets.app_sentry}}
      api_secret: ${{secrets.api_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # TODO change to beta/stable
          #flutter-version: '1.26.0-17.2.pre'
      - run: flutter doctor -v
      - run: flutter pub get
      - run: |
          cp lib/.env.dart.example lib/.env.dart
          cp android/app/build.gradle.prod android/app/build.gradle
          sed -i 's/secret/${{secrets.api_secret}}/g' lib/.env.dart
      - run: |
          echo "const FLUTTER_VERSION = const <String, String>" > lib/flutter_version.dart
          flutter --version --machine >> lib/flutter_version.dart
          echo ";" >> lib/flutter_version.dart
      - run: flutter upgrade
      - run: flutter config --enable-web
      - run: flutter build web --web-renderer html --release
      - run: |
          sed -i '/index.html/d' build/web/flutter_service_worker.js

          git config --global user.email ${{secrets.commit_email}}
          git config --global user.name ${{secrets.commit_name}}

          git clone https://${{secrets.commit_secret}}@github.com/invoiceninja/invoiceninja.git
          cd invoiceninja
          git checkout v5-develop

          cp -r ../build/web/* ./public/
          rm ./public/index.html
          git add .
          git commit -m 'New admin portal build'
          git push